'use strict';

module.exports = {
    alignItems: ['flex-start', 'flex-end', 'center', 'stretch'],
    alignSelf: ['auto', 'flex-start', 'flex-end', 'center', 'stretch'],
    backfaceVisibility: ['visible', 'hidden'],
    backgroundColor: 'string',
    borderBottomColor: 'string',
    borderBottomLeftRadius: 'number',
    borderBottomRightRadius: 'number',
    borderBottomWidth: 'number',
    borderColor: 'string',
    borderLeftColor: 'string',
    borderLeftWidth: 'number',
    borderRadius: 'number',
    borderRightColor: 'string',
    borderRightWidth: 'number',
    borderStyle: ['solid', 'dotted', 'dashed'],
    borderTopColor: 'string',
    borderTopLeftRadius: 'number',
    borderTopRightRadius: 'number',
    borderTopWidth: 'number',
    borderWidth: 'number',
    bottom: 'number',
    color: 'string',
    flex: 'number',
    flexDirection: ['row', 'column'],
    flexWrap: ['wrap', 'nowrap'],
    fontFamily: 'string',
    fontSize: 'number',
    fontStyle: ['normal', 'italic'],
    fontWeight: ['normal', 'bold', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
    height: 'number',
    justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around'],
    left: 'number',
    letterSpacing: 'number',
    lineHeight: 'number',
    margin: 'number',
    marginBottom: 'number',
    marginHorizontal: 'number',
    marginLeft: 'number',
    marginRight: 'number',
    marginTop: 'number',
    marginVertical: 'number',
    opacity: 'number',
    overflow: ['visible', 'hidden'],
    padding: 'number',
    paddingBottom: 'number',
    paddingHorizontal: 'number',
    paddingLeft: 'number',
    paddingRight: 'number',
    paddingTop: 'number',
    paddingVertical: 'number',
    position: ['absolute', 'relative'],
    resizeMode: ['cover', 'contain', 'stretch'],
    right: 'number',
    shadowColor: 'string',
    shadowOffset: {
        width: 'number',
        height: 'number'
    },
    shadowOpacity: 'number',
    shadowRadius: 'number',
    textAlign: ['auto', 'left', 'right', 'center', 'justify'],
    textDecorationLine: ['none', 'underline', 'line-through', 'underline line-through'],
    textDecorationStyle: ['solid', 'double', 'dotted', 'dashed'],
    textDecorationColor: 'string',
    tintColor: 'string',
    top: 'number',
    transform: [
        { perspective: 'number' },
        { rotate: 'string' },
        { rotateX: 'string' },
        { rotateY: 'string' },
        { rotateZ: 'string' },
        { scale: 'number' },
        { scaleX: 'number' },
        { scaleY: 'number' },
        { skewX: 'string' },
        { skewY: 'string' },
        { translateX: 'number' },
        { translateY: 'number' }
    ],
    width: 'number',
    writingDirection: ['auto', 'ltr', 'rtl']
};